<?php

declare(strict_types=1);

namespace LPhenom\Migrate\Command;

/**
 * Generates a new migration file (similar to Laravel's `php artisan make:migration`).
 *
 * Usage:
 *   vendor/bin/migrate migrate:make create_users_table
 *   vendor/bin/migrate migrate:make add_email_to_users --path=database/migrations
 *
 * Generated file:
 *   database/migrations/20260314123456_create_users_table.php
 *
 * Generated class:
 *   final class Migration20260314123456 implements MigrationInterface { ... }
 *   MigrationAutoRegistrar::register(new Migration20260314123456());
 *
 * The version is a YmdHis timestamp (e.g. 20260314123456).
 * The class name includes the timestamp only — no conflicts, easy sorting.
 *
 * KPHP notes:
 *  - date() is supported in KPHP.
 *  - is_dir(), mkdir(), file_exists(), file_put_contents() — KPHP CLI mode.
 *  - explode() + implode() + ucfirst() — KPHP-compatible string utilities.
 *  - No str_starts_with / str_ends_with / str_contains — not supported in KPHP.
 *  - fwrite(STDERR) — supported in KPHP CLI.
 *
 * Compatible with PHP 8.1+ and KPHP.
 */
final class MakeCommand implements CommandInterface
{
    /**
     * @var string
     */
    private string $migrationsPath;

    /**
     * @var string
     */
    private string $name;

    public function __construct(string $migrationsPath, string $name)
    {
        $this->migrationsPath = $migrationsPath;
        $this->name           = $name;
    }

    public function run(): int
    {
        if ($this->name === '') {
            fwrite(STDERR, 'Error: migration name is required.' . PHP_EOL);
            fwrite(STDERR, 'Usage: migrate:make <name>' . PHP_EOL);
            fwrite(STDERR, 'Example: migrate:make create_users_table' . PHP_EOL);

            return 1;
        }

        // Normalise name: lowercase, spaces/dashes to underscores
        $safeName = $this->normaliseName($this->name);

        // Ensure migrations directory exists
        if (!is_dir($this->migrationsPath)) {
            mkdir($this->migrationsPath, 0755, true);
            echo 'Created directory: ' . $this->migrationsPath . PHP_EOL;
        }

        $version   = date('YmdHis');
        $className = 'Migration' . $version;
        $fileName  = $version . '_' . $safeName . '.php';
        $filePath  = $this->migrationsPath . '/' . $fileName;

        if (file_exists($filePath)) {
            fwrite(STDERR, 'Migration already exists: ' . $filePath . PHP_EOL);

            return 1;
        }

        $content = $this->renderTemplate($version, $className, $safeName);
        file_put_contents($filePath, $content);

        echo 'Migration created: ' . $filePath . PHP_EOL;
        echo 'Class:             ' . $className . PHP_EOL;
        echo 'Version:           ' . $version . PHP_EOL;

        return 0;
    }

    /**
     * Normalise the user-supplied name:
     *   "Create users table"  → "create_users_table"
     *   "Add-email-to-users"  → "add_email_to_users"
     */
    private function normaliseName(string $name): string
    {
        // lowercase
        $name = strtolower($name);
        // spaces and dashes to underscores
        $name = str_replace([' ', '-'], '_', $name);
        // strip characters that are not alphanumeric or underscore
        $stripped = '';
        $len      = strlen($name);
        for ($i = 0; $i < $len; $i++) {
            $ch = $name[$i];
            if (
                ($ch >= 'a' && $ch <= 'z')
                || ($ch >= '0' && $ch <= '9')
                || $ch === '_'
            ) {
                $stripped .= $ch;
            }
        }

        // trim leading/trailing underscores
        return trim($stripped, '_');
    }

    /**
     * Render the migration file template.
     */
    private function renderTemplate(string $version, string $className, string $safeName): string
    {
        return '<?php' . PHP_EOL
            . PHP_EOL
            . 'declare(strict_types=1);' . PHP_EOL
            . PHP_EOL
            . '/**' . PHP_EOL
            . ' * Migration: ' . $safeName . PHP_EOL
            . ' * Version:   ' . $version . PHP_EOL
            . ' *' . PHP_EOL
            . ' * Generated by lphenom/migrate.' . PHP_EOL
            . ' * Implement up() and down() methods.' . PHP_EOL
            . ' */' . PHP_EOL
            . PHP_EOL
            . 'use LPhenom\\Db\\Contract\\ConnectionInterface;' . PHP_EOL
            . 'use LPhenom\\Db\\Migration\\MigrationInterface;' . PHP_EOL
            . 'use LPhenom\\Migrate\\MigrationAutoRegistrar;' . PHP_EOL
            . PHP_EOL
            . 'final class ' . $className . ' implements MigrationInterface' . PHP_EOL
            . '{' . PHP_EOL
            . '    public function getVersion(): string' . PHP_EOL
            . '    {' . PHP_EOL
            . '        return \'' . $version . '\';' . PHP_EOL
            . '    }' . PHP_EOL
            . PHP_EOL
            . '    public function up(ConnectionInterface $conn): void' . PHP_EOL
            . '    {' . PHP_EOL
            . '        // TODO: implement migration' . PHP_EOL
            . '        // Example:' . PHP_EOL
            . '        // $conn->execute(\'CREATE TABLE ' . $safeName . ' (...)\');' . PHP_EOL
            . '    }' . PHP_EOL
            . PHP_EOL
            . '    public function down(ConnectionInterface $conn): void' . PHP_EOL
            . '    {' . PHP_EOL
            . '        // TODO: implement rollback' . PHP_EOL
            . '        // Example:' . PHP_EOL
            . '        // $conn->execute(\'DROP TABLE IF EXISTS ' . $safeName . '\');' . PHP_EOL
            . '    }' . PHP_EOL
            . '}' . PHP_EOL
            . PHP_EOL
            . 'MigrationAutoRegistrar::register(new ' . $className . '());' . PHP_EOL;
    }
}
